theme: jekyll-theme-minimal

title: Alan Arroyo
logo: AlanImagePortfolio.jpeg
description: Data Science | Mathematics | Computer Science | Combinatorics and Optimization


github:
  is_project_page: false
