theme: jekyll-theme-minimal

title: Alan Arroyo
logo: /assets/img/logo.png
description: Data Science | Mathematics | Computer Science | Combinatorics and Optimization


github:
  is_project_page: false
